config/routes.rb
Rails.application.routes.draw do
  resources :qoutes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/qoute.rb
class Qoute < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qoutes_controller.rb
class QoutesController < ApplicationController
  before_action :set_qoute, only: [:show, :edit, :update, :destroy]

  def index
    @qoutes = Qoute.all
  end

  def show
  end

  def new
    @qoute = Qoute.new
  end

  def create
    @qoute = Qoute.new(qoute_params)

    if @qoute.save
      redirect_to qoutes_path, notice: "Qoute was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @qoute.update(qoute_params)
      redirect_to qoutes_path, notice: "Qoute was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @qoute.destroy
    redirect_to qoutes_path, notice: "Qoute was successfully destroyed."
  end

  private

  def set_qoute
    @qoute = Qoute.find(params[:id])
  end

  def qoute_params
    params.require(:qoute).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qoutes_helper.rb
module QoutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QouteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qoutes/_form.html.erb
<%= simple_form_for qoute, html: { class: "qoute form" } do |f| %>
  <% if qoute.errors.any? %>
    <div class="error-message">
      <%= qoute.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/qoutes/_qoute.html.erb
<div class="qoute">
  <%= link_to qoute.name, qoute_path(qoute) %>
  <div class="qoute__actions %>
    <div class="qoute__actions">
      <%= button_to "Delete", qoute_path(qoute), method: :delete, class: "btn btn--light" %>
      <%= link_to "Edit", edit_qoute_path(qoute), class: "btn btn--light" %>
    </div>
  </div>
</div>

app/views/qoutes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to qoutes"), qoute_path(@qoute) %>

  <div class="header">
    <h1>Edit qoute</h1>
  </div>

  <%= render "form", qoute: @qoute %>
</div>

app/views/qoutes/index.html.erb
<main class="container">
  <div class="header">
    <h1>Qoutes</h1>
    <%= link_to "New qoute", new_qoute_path, class: "btn btn--primary" %>
  </div>

  <%= render @qoutes %>
</main>

app/views/qoutes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to qoutes"), qoutes_path %>

  <div class="header">
    <h1>New qoute</h1>
  </div>

  <%= render "form", qoute: @qoute %>
</div>

app/views/qoutes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to qoutes"), qoutes_path %>
  <div class="header">
    <h1><%= @qoute.name %></h1>
  </div>
</main>